kind: ConfigMap
apiVersion: v1
metadata:
  name: widget
  namespace: jenkins
data:
  ACCESS_TOKEN: 23aff03d2f1f92a1e167c7012b752fbe7163242b9e6dee712dbf7b784d89beba
  APP_BASE_NAME: widget
  APP_SERVICE_NAME: Widget API
  THREESCALE_SERVER_BASE_URL: 3scale-admin.6dsvl.apps.shared-na46.openshift.opentlc.com
  application_yaml: |
    applications:
      - name: "widget-app"
        description: 'The widget App'
        plan: "widget-unlimited"
        account: 'john'
  applicationPlan_yaml: |
    plans:
      - systemName     : 'widget-unlimited'
        name           : 'Widget Unlimited'
        defaultPlan    : true
        published      : true
        costPerMonth   : 0.0
        setupFee       : 0.0
        trialPeriodDays: 0
      - systemName     : 'widget-limited'
        name           : 'Widget Limited'
        published      : true
        costPerMonth   : 0.0
        setupFee       : 0.0
        trialPeriodDays: 0
